language: java
jdk: oraclejdk8
sudo: false
install: true
script: ./travis.sh

before_script:
 - chmod +x travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/jvm

before_cache:
  - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
      recipients:
        - alexeyzhytnik@gmail.com
      on_success: never
      on_failure: always
