language: java

jdk:
   - oraclejdk8

sudo: false

install: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/jvm


env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

script:
  - echo ${TRAVIS_COMMIT::7}
  - echo $TRAVIS_COMMIT
  - mvn clean install

after_success:


notifications:
    email:
      recipients:
        - alexeyzhytnik@gmail.com
      on_success: never
      on_failure: always