language: java

jdk:
   - oraclejdk8

sudo: false

install: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/jvm

script:
  - echo ${TRAVIS_COMMIT::7}
  - echo $TRAVIS_COMMIT
  - mvn clean install

after_success:


notifications:
    email:
      recipients:
        - alexeyzhytnik@gmail.com
      on_success: never
      on_failure: always